import type { Metadata } from "next";
import { Belleza } from "next/font/google";
import "./../globals.css"
import Navbar from "../homeUi/navbar";
import Footer from "../homeUi/footer";
import MobileNavbar from "../homeUi/mobileNav";


// sets global font to Belleza using google fonts
const inter = Belleza({ 
  weight: '400',
  style: 'normal',
  subsets: ['latin']
  });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head></head>
      <body className={inter.className}>
        {/* Implements both navbar and mobilenavbar components, will return based on screen size */}
        <div className="border-2 border-slate-300">
        <Navbar />
        </div>
        <MobileNavbar />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
