import type { Metadata } from "next";
import { Belleza } from "next/font/google";
import "./../globals.css"
import Navbar from "../homeUi/navbar";
import Footer from "../homeUi/footer";
import MobileNavbar from "../homeUi/mobileNav";
import Image from "next/image";

// sets global font to Belleza using google fonts
const inter = Belleza({ 
  weight: '400',
  style: 'normal',
  subsets: ['latin']
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head></head>
      <body className={inter.className}>
        {/* Implements both navbar and mobilenavbar components, will return based on screen size */}
        <div className="home-body">
          <div className="navbar-container">
            <div className="menu-button">
              <MobileNavbar />
            </div>
            <div className="nav-logo-mobile">
              <Image src="/logotransparent.png" width={80} height={80} alt="Revived Relics" />
            </div>
            <Navbar />
          </div>
        </div>
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
