import type { Metadata } from "next";
import { Belleza } from "next/font/google";

const inter = Belleza({ 
  weight: '400',
  style: 'normal',
  subsets: ['latin']
  });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AdminLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head></head>
      <body className={inter.className}>
        <main>{children}</main>
      </body>
    </html>
  );
}
